-- 0007_application_resumes.sql
-- Private bucket for applicant resumes.
-- Public applications still submit through server actions; staff can read
-- private files through signed URLs generated by the service-role client.

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'application-resumes',
  'application-resumes',
  false,
  5242880,
  array[
    'application/pdf',
    'application/msword',
    'application/vnd.openxmlformats-officedocument.wordprocessingml.document'
  ]
)
on conflict (id) do update
set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "application_resumes_staff_read" on storage.objects;
create policy "application_resumes_staff_read"
  on storage.objects for select to authenticated
  using (bucket_id = 'application-resumes' and public.is_staff(auth.uid()));

drop policy if exists "application_resumes_staff_write" on storage.objects;
create policy "application_resumes_staff_write"
  on storage.objects for insert to authenticated
  with check (bucket_id = 'application-resumes' and public.is_staff(auth.uid()));

drop policy if exists "application_resumes_staff_update" on storage.objects;
create policy "application_resumes_staff_update"
  on storage.objects for update to authenticated
  using (bucket_id = 'application-resumes' and public.is_staff(auth.uid()))
  with check (bucket_id = 'application-resumes' and public.is_staff(auth.uid()));

drop policy if exists "application_resumes_staff_delete" on storage.objects;
create policy "application_resumes_staff_delete"
  on storage.objects for delete to authenticated
  using (bucket_id = 'application-resumes' and public.is_staff(auth.uid()));

drop policy if exists "applications_public_insert" on public.applications;
create policy "applications_public_insert" on public.applications
  for insert
  with check (
    exists (
      select 1
      from public.jobs
      where jobs.id = applications.job_id
        and jobs.is_open = true
    )
  );
